"""Create tables heroes, powers, heropowers

Revision ID: 41c92a91bf95
Revises: 9bc2ba3659b6
Create Date: 2024-01-29 08:22:41.906111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c92a91bf95'
down_revision = '9bc2ba3659b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
